services:
  app:
    build:
      context: .
    image: devinterview-pro-app
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16
    env_file:
      - .env.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
