name: devinterview-pro
services:
- name: web
  source_dir: /
  github:
    repo: your-username/devinterview-pro
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: SESSION_SECRET
    type: SECRET
  - key: STRIPE_SECRET_KEY
    type: SECRET
  - key: VITE_STRIPE_PUBLISHABLE_KEY_LIVE
    type: SECRET
  - key: USE_SIMPLE_ROUTES
    value: "false"

databases:
- name: db
  engine: PG
  num_nodes: 1
  size: db-s-dev-database